import Navbar from "@/components/Navbar";
import "./globals.css";

import { dbConnect } from "@/services/mongo";
import AuthProvider from "./providers/AuthProvider";

export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
    await dbConnect();
    return (
        <html lang="en">
            <body>
                <AuthProvider>
                    <Navbar />
                    <main className="py-8">{children}
                      
                    </main>
                </AuthProvider>
            </body>
        </html>
    );
}
