
import Navbar from "@/components/Navbar";
import "./globals.css";

 import { dbConnect } from "@/services/mongo";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  await dbConnect();
  return (
    <html lang="en">
      <body>
        <Navbar />
                {children}
      </body>
    </html>
  );
}
 